# Generated by Django 4.2.3 on 2023-12-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('synonym', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': '1st lvl Taxonomy',
                'verbose_name_plural': '1st lvl Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_text', models.CharField(default='Send CV', max_length=1024)),
                ('hero_title', models.CharField(max_length=1024)),
                ('hero_desc', models.CharField(max_length=1024)),
                ('about_title', models.CharField(max_length=1024)),
                ('about_description', models.CharField(max_length=1024)),
                ('about_subtitle_1', models.CharField(max_length=1024)),
                ('about_text_1', models.CharField(max_length=1024)),
                ('about_subtitle_2', models.CharField(default='English - Intermediate', max_length=256)),
                ('about_text_2', models.CharField(max_length=1024)),
                ('steps_title', models.CharField(max_length=1024)),
                ('feat_title', models.CharField(max_length=1024)),
                ('feat_cta', models.CharField(max_length=1024)),
                ('feat_find', models.CharField(max_length=1024)),
                ('feat_time', models.CharField(max_length=1024)),
                ('feat_law', models.CharField(max_length=1024)),
                ('feat_happy', models.CharField(max_length=1024)),
                ('form', models.CharField(max_length=1024)),
                ('bot_team', models.CharField(max_length=1024)),
                ('bot_qa', models.CharField(max_length=1024)),
                ('bot_chat', models.CharField(max_length=1024)),
                ('bot_att', models.CharField(max_length=1024)),
                ('bot_lng', models.CharField(max_length=1024)),
                ('reviews_title', models.CharField(default='Reviews', max_length=1024)),
                ('hot_scenarios', models.CharField(default='Hot scenarios', max_length=1024)),
                ('we_are_employed', models.CharField(default='We have already employed almost 260 people', max_length=1024)),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landings',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code_a2', models.CharField(blank=True, max_length=2)),
                ('google_lang_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, editable=False, max_length=310, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True)),
                ('text_html', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.language')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='TechnologyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Technology Item',
                'verbose_name_plural': 'Technology Items',
            },
        ),
        migrations.CreateModel(
            name='SecondLevelTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(blank=True, to='eij.technologyitem')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.firstleveltaxonomy')),
            ],
            options={
                'verbose_name': '2nd lvl Taxonomy',
                'verbose_name_plural': '2nd lvl Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='ScenarioRawKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Raw KeyWord',
                'verbose_name_plural': 'Scenario Raw KeyWords',
            },
        ),
        migrations.CreateModel(
            name='ScenarioMetaTranslated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='Categories', max_length=512)),
                ('more', models.CharField(blank=True, max_length=512)),
                ('apply_for_job', models.CharField(blank=True, max_length=512)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eij.language')),
            ],
            options={
                'verbose_name': 'Scenario Meta',
                'verbose_name_plural': 'Scenario Meta',
            },
        ),
        migrations.CreateModel(
            name='ScenarioHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Header',
                'verbose_name_plural': 'Scenario Headers',
            },
        ),
        migrations.CreateModel(
            name='ScenarioGoogleKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Google KeyWord',
                'verbose_name_plural': 'Scenario Google KeyWords',
            },
        ),
        migrations.CreateModel(
            name='ScenarioDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=90)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Description',
                'verbose_name_plural': 'Scenario Descriptions',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eij.scenariometatranslated'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='eij.scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eij.firstleveltaxonomy'),
        ),
        migrations.CreateModel(
            name='LanguageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_scenarios', models.CharField(blank=True, max_length=512)),
                ('menu_for_business', models.CharField(blank=True, max_length=512)),
                ('menu_send_cv', models.CharField(blank=True, max_length=512)),
                ('menu_categories', models.CharField(blank=True, max_length=512)),
                ('footer_bot', models.CharField(blank=True, max_length=512)),
                ('footer_privacy', models.CharField(blank=True, max_length=512)),
                ('footer_cookie', models.CharField(blank=True, max_length=512)),
                ('footer_rights', models.CharField(blank=True, max_length=512)),
                ('err_title', models.CharField(blank=True, max_length=512)),
                ('err_subtitle', models.CharField(blank=True, max_length=512)),
                ('err_text', models.CharField(blank=True, max_length=512)),
                ('err_link', models.CharField(blank=True, max_length=512)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eij.language')),
            ],
            options={
                'verbose_name': 'Language Meta',
                'verbose_name_plural': 'Languages Meta',
            },
        ),
        migrations.CreateModel(
            name='LandingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('text', models.CharField(max_length=1024)),
                ('time', models.SmallIntegerField()),
                ('label', models.CharField(max_length=1024)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='eij.landing')),
            ],
            options={
                'verbose_name': 'Landing Step',
                'verbose_name_plural': 'Landing Steps',
            },
        ),
        migrations.CreateModel(
            name='LandingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=1024)),
                ('full_name', models.CharField(max_length=1024)),
                ('position', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='eij.landing')),
            ],
            options={
                'verbose_name': 'Landing Feedback',
                'verbose_name_plural': 'Landing Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='landing',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eij.language'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code_a2', models.CharField(max_length=2, unique=True)),
                ('google_location_id', models.SmallIntegerField(blank=True, null=True)),
                ('languages', models.ManyToManyField(blank=True, to='eij.language')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('budget_usd', models.IntegerField(default=333)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eij.language')),
            ],
            options={
                'verbose_name': 'Google ADs Campaign',
                'verbose_name_plural': 'Google ADs Campaigns',
            },
        ),
    ]
