# Generated by Django 4.2.3 on 2023-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eij', '0002_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
