# Generated by Django 4.2.3 on 2023-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eij', '0004_page_pagedescription_pagegooglekeyword_pageheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ads_task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='ads_task_status',
            field=models.CharField(choices=[(0, ''), (1, 'Started'), (2, 'Successfully Completed'), (3, 'Failed')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_task_status',
            field=models.CharField(choices=[(0, ''), (1, 'Started'), (2, 'Successfully Completed'), (3, 'Failed')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='page',
            name='seodata_task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seodata_task_status',
            field=models.CharField(choices=[(0, ''), (1, 'Started'), (2, 'Successfully Completed'), (3, 'Failed')], default=0, max_length=1),
        ),
    ]
