# Generated by Django 4.2.3 on 2023-12-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eij', '0006_alter_page_ads_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ads_task_status',
            field=models.CharField(choices=[('0', ''), ('1', 'Started'), ('2', 'Successfully Completed'), ('3', 'Failed')], default=0, max_length=1, verbose_name='ADs'),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords_task_status',
            field=models.CharField(choices=[('0', ''), ('1', 'Started'), ('2', 'Successfully Completed'), ('3', 'Failed')], default=0, max_length=1, verbose_name='Google Keywords'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seodata_task_status',
            field=models.CharField(choices=[('0', ''), ('1', 'Started'), ('2', 'Successfully Completed'), ('3', 'Failed')], default=0, max_length=1, verbose_name='SEO data'),
        ),
    ]
