# Generated by Django 4.2.3 on 2023-12-27 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eij.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eij', '0008_alter_page_ads_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(default=eij.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(default=eij.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='created_by',
            field=models.ForeignKey(default=eij.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_websites', to=settings.AUTH_USER_MODEL),
        ),
    ]
